-- CREATE DATABASE Hotel_Manager
USE Hotel_Manager

--DROP DATABASE Hotel_Manager

SET DATEFORMAT DMY

-- PHAN TAO BANG --
CREATE TABLE NGUOIDUNG
(
TenDangNhap nvarchar(20) COLLATE Latin1_General_CS_AS PRIMARY KEY, 
MatKhau nvarchar(20) COLLATE Latin1_General_CS_AS,
LoaiNguoiDung int,
);

CREATE TABLE LOAIPHONG -- Tao bang loai phong de thuc hien viec  phat trien nhieu loai phong.
(
MaLoaiPhong int PRIMARY KEY IDENTITY,
TenLoaiPhong nvarchar(40),
DonGia money,
SucChua tinyint,

);

CREATE TABLE PHONG
(
SoPhong int PRIMARY KEY IDENTITY, -- Dinh danh 
MaLoaiPhong int,
TinhTrang nvarchar(40) DEFAULT('TRONG'),
GhiChu nvarchar(40),
);

CREATE TABLE PHIEUTHUEPHONG
(
SoPTP int PRIMARY KEY IDENTITY, -- Dinh danh 
NgayLap date,
);

CREATE TABLE CT_PTP
(
MaCT_PTP int PRIMARY KEY IDENTITY, -- Dinh danh 
SoPTP int,
SoPhong int,
MaKH int,
GhiChu nvarchar(40),
);


CREATE TABLE KHACHHANG
(
MaKH int PRIMARY KEY IDENTITY,
TenKH nvarchar(40),
DinhDanh nvarchar (40),
);

CREATE TABLE PHIEUTHANHTOAN
(
SoPTT int PRIMARY KEY IDENTITY,
NgayTT date,
MaKH int,
);

CREATE TABLE CT_PTT
(
MaCT_PTT int PRIMARY KEY IDENTITY,
SoPTT int,
SoPhong int,
SoNgayThue int,
MaDV int,
ThanhTien money,
);

CREATE TABLE DICHVU 
(
MaDV int PRIMARY KEY IDENTITY,
TenDV nvarchar(40),
DonGia money,

);

CREATE TABLE BAOCAO
(
Ma_BC int PRIMARY KEY IDENTITY,
Thang int,

);

CREATE TABLE CT_BAOCAO
(
Ma_CTBC int PRIMARY KEY IDENTITY,
Ma_BC int,
SoPhong int,
DoanhThu money,
);

CREATE TABLE CHUCVU
(
MaCV int PRIMARY KEY IDENTITY,
TenCV nvarchar(40),
PhuCap float,
);

CREATE TABLE NHANVIEN
(
MaNV int PRIMARY KEY IDENTITY,
TenNV nvarchar(40),
MaCV int,
DinhDanh int,
DiaChi nvarchar(40),
);

CREATE TABLE BAOCAO_LUONG
(
Ma_BC int PRIMARY KEY IDENTITY,
Thang int,
);

CREATE TABLE BAOCAOCT_LUONG
(
MaCT_BC int PRIMARY KEY IDENTITY,
Ma_BC int,
MaNV int,
Thanh_Tien money,
)

-- PHAN TAO KHOA NGOAI --
ALTER TABLE PHONG ADD
CONSTRAINT FK_PHONG_MaLoaiPhong FOREIGN KEY (MaLoaiPhong) REFERENCES LOAIPHONG(MaLoaiPhong)

ALTER TABLE CT_PTP ADD
CONSTRAINT FK_CTPTP_SoPTP FOREIGN KEY (SoPTP) REFERENCES PHIEUTHUEPHONG(SoPTP),
CONSTRAINT FK_CTPTP_SoPhong FOREIGN KEY (SoPhong) REFERENCES PHONG(SoPhong),
CONSTRAINT FK_CTPTP_MaKH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)

ALTER TABLE PHIEUTHANHTOAN ADD
CONSTRAINT FK_PHIEUTHANHTOAN_MaKH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)

ALTER TABLE CT_PTT ADD
CONSTRAINT FK_CTPTT_SoPTT FOREIGN KEY (SoPTT) REFERENCES PHIEUTHANHTOAN(SoPTT),
CONSTRAINT FK_CTPTT_SoPhong FOREIGN KEY (SoPhong) REFERENCES PHONG(SoPhong),
CONSTRAINT FK_CTPTT_MaDV FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)

ALTER TABLE CT_BAOCAO ADD
CONSTRAINT FK_CTBAOCAO_MaBC FOREIGN KEY (Ma_BC) REFERENCES BAOCAO(Ma_BC),
CONSTRAINT FK_CTBAOCAO_SoPhong FOREIGN KEY (SoPhong) REFERENCES Phong(SoPhong)

ALTER TABLE BAOCAOCT_LUONG ADD
CONSTRAINT FK_BAOCAOCTLUONG_MaBC FOREIGN KEY (Ma_BC) REFERENCES BAOCAO_LUONG(Ma_BC),
CONSTRAINT FK_BAOCAOCTLUONG_MaNV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE NHANVIEN ADD
CONSTRAINT FK_NHANVIEN_MaCV FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV)