/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotelmanager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admins
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Source_code model = new Source_code();
    List<Integer> DichVu = model.LayMaDichVu();
    List<Integer> ChucVu = model.LayMaChucVu();
    public Admin() {
        
        initComponents();
        
        
        String rowCV[] = new String[3];
        String rowDV[] = new String[3];
        DefaultTableModel Tablemodel = (DefaultTableModel) tb_DV1.getModel();
     
        for (int MaCV : ChucVu) {
            int Luong = model.LayLuongChucVu(MaCV);
            String TenCV = model.LayTenChucVu(MaCV);
            rowCV[0] = Integer.toString(Tablemodel.getRowCount()+1);
            rowCV[1] = TenCV;
            rowCV[2] = Integer.toString(Luong);
            Tablemodel.addRow(rowCV);
            
        }
        Tablemodel = (DefaultTableModel) tb_DV.getModel();
        
         for (int MaDV : DichVu) {
            
            int Luong = model.LayDonGiaDichVu(MaDV);
            String TenDV = model.LayTenDichVu(MaDV);
            rowDV[0] = Integer.toString(Tablemodel.getRowCount()+1);
            rowDV[1] = TenDV;
            rowDV[2] = Integer.toString(Luong);
            Tablemodel.addRow(rowDV);
            
        }



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tabbedPanel = new javax.swing.JTabbedPane();
        tabpn_NV = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_NV = new javax.swing.JTable();
        btn_Salary = new javax.swing.JButton();
        btn_Delete_NV = new javax.swing.JButton();
        btn_Add_NV = new javax.swing.JButton();
        btn_Adjust_NV = new javax.swing.JButton();
        tabpn_DV = new javax.swing.JPanel();
        btn_Add_DV = new javax.swing.JButton();
        btn_Delete_DV = new javax.swing.JButton();
        btn_Adjust_DV = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txb_TenDV = new javax.swing.JTextField();
        txb_GiaDV = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_DV = new javax.swing.JTable();
        tabpn_Phong = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txb_GiaLPhong = new javax.swing.JTextField();
        txb_TenLPhong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txb_SucChua = new javax.swing.JTextField();
        btn_Add_LP = new javax.swing.JButton();
        btn_Adjust_LP = new javax.swing.JButton();
        btn_Delete_LP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_LPhong = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txb_SoPhong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txb_GhiChu = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_Phong = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        combob_LoaiPhong = new javax.swing.JComboBox<>();
        combob_TinhTrang = new javax.swing.JComboBox<>();
        btn_Add_Phong = new javax.swing.JButton();
        btn_Adjust_Phong = new javax.swing.JButton();
        btn_Delete_Phong = new javax.swing.JButton();
        tabpn_ChucVu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txb_TenDV1 = new javax.swing.JTextField();
        txb_GiaDV1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_DV1 = new javax.swing.JTable();
        btn_Add_DV1 = new javax.swing.JButton();
        btn_Delete_DV1 = new javax.swing.JButton();
        btn_Adjust_DV1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tabbedPanel.setBackground(new java.awt.Color(255, 102, 102));
        tabbedPanel.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 24)); // NOI18N
        tabbedPanel.setRequestFocusEnabled(false);

        tabpn_NV.setBackground(new java.awt.Color(255, 204, 204));
        tabpn_NV.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 18)); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        tb_NV.setBackground(new java.awt.Color(255, 204, 204));
        tb_NV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_NV.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_NV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Nhân viên", "Chức vụ", "CCCD", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_NV.setGridColor(new java.awt.Color(0, 0, 0));
        tb_NV.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_NV.setShowGrid(false);
        tb_NV.setShowHorizontalLines(true);
        tb_NV.setShowVerticalLines(true);
        tb_NV.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_NV);

        btn_Salary.setBackground(new java.awt.Color(255, 204, 204));
        btn_Salary.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Salary.setText("Lương");
        btn_Salary.setToolTipText("");
        btn_Salary.setBorder(null);

        btn_Delete_NV.setBackground(new java.awt.Color(255, 204, 204));
        btn_Delete_NV.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Delete_NV.setText("Xóa");
        btn_Delete_NV.setToolTipText("");
        btn_Delete_NV.setBorder(null);

        btn_Add_NV.setBackground(new java.awt.Color(255, 204, 204));
        btn_Add_NV.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Add_NV.setText("Thêm");
        btn_Add_NV.setToolTipText("");
        btn_Add_NV.setBorder(null);

        btn_Adjust_NV.setBackground(new java.awt.Color(255, 204, 204));
        btn_Adjust_NV.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Adjust_NV.setText("Sửa");
        btn_Adjust_NV.setToolTipText("");
        btn_Adjust_NV.setBorder(null);

        javax.swing.GroupLayout tabpn_NVLayout = new javax.swing.GroupLayout(tabpn_NV);
        tabpn_NV.setLayout(tabpn_NVLayout);
        tabpn_NVLayout.setHorizontalGroup(
            tabpn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_NVLayout.createSequentialGroup()
                .addGroup(tabpn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpn_NVLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabpn_NVLayout.createSequentialGroup()
                        .addGroup(tabpn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabpn_NVLayout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(btn_Delete_NV))
                            .addGroup(tabpn_NVLayout.createSequentialGroup()
                                .addGap(0, 433, Short.MAX_VALUE)
                                .addComponent(btn_Add_NV)))
                        .addGap(119, 119, 119)
                        .addGroup(tabpn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Salary)
                            .addComponent(btn_Adjust_NV))
                        .addGap(243, 243, 243)))
                .addContainerGap())
        );
        tabpn_NVLayout.setVerticalGroup(
            tabpn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabpn_NVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabpn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salary)
                    .addComponent(btn_Add_NV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabpn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Adjust_NV)
                    .addComponent(btn_Delete_NV))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("NHÂN VIÊN", tabpn_NV);

        tabpn_DV.setBackground(new java.awt.Color(255, 204, 204));

        btn_Add_DV.setBackground(new java.awt.Color(255, 204, 204));
        btn_Add_DV.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Add_DV.setText("Thêm");
        btn_Add_DV.setToolTipText("");
        btn_Add_DV.setBorder(null);
        btn_Add_DV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_DVActionPerformed(evt);
            }
        });

        btn_Delete_DV.setBackground(new java.awt.Color(255, 204, 204));
        btn_Delete_DV.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Delete_DV.setText("Xóa");
        btn_Delete_DV.setToolTipText("");
        btn_Delete_DV.setBorder(null);
        btn_Delete_DV.setEnabled(false);
        btn_Delete_DV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Delete_DVActionPerformed(evt);
            }
        });

        btn_Adjust_DV.setBackground(new java.awt.Color(255, 204, 204));
        btn_Adjust_DV.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Adjust_DV.setText("Sửa");
        btn_Adjust_DV.setToolTipText("");
        btn_Adjust_DV.setBorder(null);
        btn_Adjust_DV.setEnabled(false);
        btn_Adjust_DV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Adjust_DVActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SVN-Nexa Light", 0, 36)); // NOI18N
        jLabel2.setText("Giá tiền:");

        jLabel3.setFont(new java.awt.Font("SVN-Nexa Light", 0, 36)); // NOI18N
        jLabel3.setText("Tên dịch vụ:");

        txb_TenDV.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        txb_GiaDV.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        jScrollPane2.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        tb_DV.setBackground(new java.awt.Color(255, 204, 204));
        tb_DV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_DV.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_DV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên dịch vụ", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_DV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tb_DV.setGridColor(new java.awt.Color(0, 0, 0));
        tb_DV.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_DV.setShowGrid(false);
        tb_DV.setShowHorizontalLines(true);
        tb_DV.setShowVerticalLines(true);
        tb_DV.getTableHeader().setReorderingAllowed(false);
        tb_DV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_DV);

        javax.swing.GroupLayout tabpn_DVLayout = new javax.swing.GroupLayout(tabpn_DV);
        tabpn_DV.setLayout(tabpn_DVLayout);
        tabpn_DVLayout.setHorizontalGroup(
            tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_DVLayout.createSequentialGroup()
                .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpn_DVLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabpn_DVLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_Delete_DV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Add_DV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Adjust_DV, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                    .addGroup(tabpn_DVLayout.createSequentialGroup()
                        .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txb_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txb_GiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabpn_DVLayout.setVerticalGroup(
            tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_DVLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txb_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txb_GiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(tabpn_DVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabpn_DVLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Add_DV)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Delete_DV)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Adjust_DV)
                        .addGap(120, 120, 120)))
                .addContainerGap())
        );

        tabbedPanel.addTab("Dịch vụ", tabpn_DV);

        tabpn_Phong.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("SVN-Nexa Light", 0, 30)); // NOI18N
        jLabel4.setText("Tên loại phòng:");

        jLabel5.setFont(new java.awt.Font("SVN-Nexa Light", 0, 30)); // NOI18N
        jLabel5.setText("Đơn giá:");

        txb_GiaLPhong.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        txb_TenLPhong.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SVN-Nexa Light", 0, 30)); // NOI18N
        jLabel6.setText("Sức chứa:");

        txb_SucChua.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        btn_Add_LP.setBackground(new java.awt.Color(255, 204, 204));
        btn_Add_LP.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 48)); // NOI18N
        btn_Add_LP.setText("T");
        btn_Add_LP.setToolTipText("");
        btn_Add_LP.setBorder(null);

        btn_Adjust_LP.setBackground(new java.awt.Color(255, 204, 204));
        btn_Adjust_LP.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 48)); // NOI18N
        btn_Adjust_LP.setText("S");
        btn_Adjust_LP.setToolTipText("");
        btn_Adjust_LP.setBorder(null);

        btn_Delete_LP.setBackground(new java.awt.Color(255, 204, 204));
        btn_Delete_LP.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 48)); // NOI18N
        btn_Delete_LP.setText("X");
        btn_Delete_LP.setToolTipText("");
        btn_Delete_LP.setBorder(null);

        jScrollPane3.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        tb_LPhong.setBackground(new java.awt.Color(255, 204, 204));
        tb_LPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_LPhong.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_LPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên loại phòng", "Đơn giá", "Sức chứa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_LPhong.setGridColor(new java.awt.Color(0, 0, 0));
        tb_LPhong.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_LPhong.setShowGrid(false);
        tb_LPhong.setShowHorizontalLines(true);
        tb_LPhong.setShowVerticalLines(true);
        tb_LPhong.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tb_LPhong);

        jLabel7.setFont(new java.awt.Font("SVN-Nexa Light", 0, 30)); // NOI18N
        jLabel7.setText("Số phòng:");

        txb_SoPhong.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("SVN-Nexa Light", 0, 30)); // NOI18N
        jLabel8.setText("Loại phòng:");

        jLabel9.setFont(new java.awt.Font("SVN-Nexa Light", 0, 30)); // NOI18N
        jLabel9.setText("Ghi chú:");

        txb_GhiChu.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        jScrollPane4.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        tb_Phong.setBackground(new java.awt.Color(255, 204, 204));
        tb_Phong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_Phong.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_Phong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Số phòng", "Loại phòng", "Tình trạng", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Phong.setGridColor(new java.awt.Color(0, 0, 0));
        tb_Phong.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_Phong.setShowGrid(false);
        tb_Phong.setShowHorizontalLines(true);
        tb_Phong.setShowVerticalLines(true);
        tb_Phong.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tb_Phong);

        jLabel10.setFont(new java.awt.Font("SVN-Nexa Light", 0, 30)); // NOI18N
        jLabel10.setText("Tình trạng:");

        combob_LoaiPhong.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        combob_TinhTrang.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        btn_Add_Phong.setBackground(new java.awt.Color(255, 204, 204));
        btn_Add_Phong.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 48)); // NOI18N
        btn_Add_Phong.setText("T");
        btn_Add_Phong.setToolTipText("");
        btn_Add_Phong.setBorder(null);

        btn_Adjust_Phong.setBackground(new java.awt.Color(255, 204, 204));
        btn_Adjust_Phong.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 48)); // NOI18N
        btn_Adjust_Phong.setText("S");
        btn_Adjust_Phong.setToolTipText("");
        btn_Adjust_Phong.setBorder(null);

        btn_Delete_Phong.setBackground(new java.awt.Color(255, 204, 204));
        btn_Delete_Phong.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 48)); // NOI18N
        btn_Delete_Phong.setText("X");
        btn_Delete_Phong.setToolTipText("");
        btn_Delete_Phong.setBorder(null);

        javax.swing.GroupLayout tabpn_PhongLayout = new javax.swing.GroupLayout(tabpn_Phong);
        tabpn_Phong.setLayout(tabpn_PhongLayout);
        tabpn_PhongLayout.setHorizontalGroup(
            tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_PhongLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpn_PhongLayout.createSequentialGroup()
                        .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txb_SucChua)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txb_GiaLPhong)
                            .addComponent(txb_TenLPhong)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txb_SoPhong)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txb_GhiChu)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(tabpn_PhongLayout.createSequentialGroup()
                                .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combob_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combob_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(tabpn_PhongLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btn_Add_LP)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Adjust_LP)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Delete_LP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Add_Phong)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Adjust_Phong)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Delete_Phong)
                        .addGap(142, 142, 142))))
        );
        tabpn_PhongLayout.setVerticalGroup(
            tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_PhongLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabpn_PhongLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txb_TenLPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txb_GiaLPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txb_SucChua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabpn_PhongLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txb_SoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combob_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combob_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txb_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabpn_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Add_LP)
                    .addComponent(btn_Adjust_LP)
                    .addComponent(btn_Delete_LP)
                    .addComponent(btn_Add_Phong)
                    .addComponent(btn_Adjust_Phong)
                    .addComponent(btn_Delete_Phong))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Phòng", tabpn_Phong);

        tabpn_ChucVu.setBackground(new java.awt.Color(255, 204, 204));

        jLabel11.setFont(new java.awt.Font("SVN-Nexa Light", 0, 36)); // NOI18N
        jLabel11.setText("Tên chức vụ:");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("SVN-Nexa Light", 0, 36)); // NOI18N
        jLabel12.setText("Lương cơ bản:");

        txb_TenDV1.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        txb_GiaDV1.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N
        txb_GiaDV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txb_GiaDV1ActionPerformed(evt);
            }
        });

        jScrollPane5.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        tb_DV1.setBackground(new java.awt.Color(255, 204, 204));
        tb_DV1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_DV1.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_DV1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên chức vụ", "Lương cơ bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_DV1.setGridColor(new java.awt.Color(0, 0, 0));
        tb_DV1.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_DV1.setShowGrid(false);
        tb_DV1.setShowHorizontalLines(true);
        tb_DV1.setShowVerticalLines(true);
        tb_DV1.getTableHeader().setReorderingAllowed(false);
        tb_DV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DV1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tb_DV1);

        btn_Add_DV1.setBackground(new java.awt.Color(255, 204, 204));
        btn_Add_DV1.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Add_DV1.setText("Thêm");
        btn_Add_DV1.setToolTipText("");
        btn_Add_DV1.setBorder(null);
        btn_Add_DV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_DV1ActionPerformed(evt);
            }
        });

        btn_Delete_DV1.setBackground(new java.awt.Color(255, 204, 204));
        btn_Delete_DV1.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Delete_DV1.setText("Xóa");
        btn_Delete_DV1.setToolTipText("");
        btn_Delete_DV1.setBorder(null);
        btn_Delete_DV1.setEnabled(false);
        btn_Delete_DV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Delete_DV1ActionPerformed(evt);
            }
        });

        btn_Adjust_DV1.setBackground(new java.awt.Color(255, 204, 204));
        btn_Adjust_DV1.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Adjust_DV1.setText("Sửa");
        btn_Adjust_DV1.setToolTipText("");
        btn_Adjust_DV1.setBorder(null);
        btn_Adjust_DV1.setEnabled(false);
        btn_Adjust_DV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Adjust_DV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabpn_ChucVuLayout = new javax.swing.GroupLayout(tabpn_ChucVu);
        tabpn_ChucVu.setLayout(tabpn_ChucVuLayout);
        tabpn_ChucVuLayout.setHorizontalGroup(
            tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_ChucVuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(tabpn_ChucVuLayout.createSequentialGroup()
                        .addGroup(tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(tabpn_ChucVuLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_Delete_DV1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Add_DV1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Adjust_DV1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txb_TenDV1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txb_GiaDV1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        tabpn_ChucVuLayout.setVerticalGroup(
            tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_ChucVuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txb_TenDV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txb_GiaDV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tabpn_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabpn_ChucVuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(tabpn_ChucVuLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btn_Add_DV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Delete_DV1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Adjust_DV1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabbedPanel.addTab("Chức vụ", tabpn_ChucVu);

        jLabel1.setFont(new java.awt.Font("SVN-Nexa Rush Handmade Extended", 1, 48)); // NOI18N
        jLabel1.setText("QUẢN LÝ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tb_DV1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DV1MouseClicked
       int index = tb_DV1.getSelectedRow();
       if(evt.getClickCount()==2) {
       tb_DV1.clearSelection();
       txb_TenDV1.setText("");
       txb_GiaDV1.setText("");
       btn_Add_DV1.setEnabled(true);
       btn_Delete_DV1.setEnabled(false);
       btn_Adjust_DV1.setEnabled(false);
       }
       else {
       btn_Add_DV1.setEnabled(false);
       btn_Delete_DV1.setEnabled(true);
       btn_Adjust_DV1.setEnabled(true);
  
       //DefaultTableModel Tablemodel = (DefaultTableModel) tb_DV1.getModel();
      
       txb_TenDV1.setText((String)tb_DV1.getValueAt(index,1));
       txb_GiaDV1.setText((String)tb_DV1.getValueAt(index,2));
       }
    }//GEN-LAST:event_tb_DV1MouseClicked

    private void btn_Add_DV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_DV1ActionPerformed
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn thêm","Thêm dữ liệu",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.NO_OPTION) return;
        Connection con = model.GetCon();
        String TenCV = txb_TenDV1.getText();
        String LuongCoBan = txb_GiaDV1.getText();
        String sql = "EXEC ThemChucVu ?,?";
        try{
            PreparedStatement pres = con.prepareStatement(sql);
            pres.setString(1,TenCV);
            pres.setInt(2,Integer.parseInt(LuongCoBan));

            pres.executeUpdate();
            ChucVu = model.LayMaChucVu();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            DefaultTableModel Tablemodel = (DefaultTableModel) tb_DV1.getModel();
            String [] row = {Integer.toString(Tablemodel.getRowCount()+1),TenCV,LuongCoBan};
            Tablemodel.addRow(row);
            
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, "Lỗi");}
    }//GEN-LAST:event_btn_Add_DV1ActionPerformed

    private void txb_GiaDV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txb_GiaDV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txb_GiaDV1ActionPerformed

    private void btn_Delete_DV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Delete_DV1ActionPerformed
       int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa","Xóa dữ liệu",JOptionPane.YES_NO_OPTION);
       if(ret == JOptionPane.NO_OPTION) return;
       Connection con = model.GetCon();
       int index = tb_DV1.getSelectedRow();
       int MaCV = ChucVu.get(index) ;
       
       //int MaCV = model.LayMaChucVu(TenCV);
       String sql = "DELETE FROM CHUCVU WHERE MaCV=?";
       DefaultTableModel Tablemodel = (DefaultTableModel) tb_DV1.getModel();
       try{
            PreparedStatement pres = con.prepareStatement(sql);
            pres.setInt(1,MaCV);
            pres.executeUpdate();
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            ChucVu = model.LayMaChucVu();
            Tablemodel.removeRow(tb_DV1.getSelectedRow());
            tb_DV1.clearSelection();
            txb_TenDV1.setText("");
            txb_GiaDV1.setText("");
            btn_Add_DV1.setEnabled(true);
            btn_Delete_DV1.setEnabled(false);
            btn_Adjust_DV1.setEnabled(false);
            for(int i=0;i<Tablemodel.getRowCount();i++) {
                tb_DV1.setValueAt(i+1, i, 0);
            
            }
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, "Lỗi");}
       
    }//GEN-LAST:event_btn_Delete_DV1ActionPerformed

    private void btn_Adjust_DV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Adjust_DV1ActionPerformed
       int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn sửa","Sửa dữ liệu",JOptionPane.YES_NO_OPTION);
       if(ret == JOptionPane.NO_OPTION) return;
       int index = tb_DV1.getSelectedRow();
       Connection con = model.GetCon();
       String TenCV = txb_TenDV1.getText();
       String LuongCoBan = txb_GiaDV1.getText();
       int MaCV = ChucVu.get(index) ;
    
       
       String sql = "UPDATE CHUCVU SET TenCV=?,LUONGCOBAN=? WHERE MaCV=?";
       try{
            PreparedStatement pres = con.prepareStatement(sql);
            pres.setString(1,TenCV);
            pres.setInt(2,Integer.parseInt(LuongCoBan));
            pres.setInt(3,MaCV);
            pres.executeUpdate();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            tb_DV1.setValueAt(TenCV, index, 1);
            tb_DV1.setValueAt(LuongCoBan, index, 2);
            txb_TenDV1.setText("");
            txb_GiaDV1.setText("");
            btn_Add_DV1.setEnabled(true);
            btn_Delete_DV1.setEnabled(false);
            btn_Adjust_DV1.setEnabled(false);
        
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, "Lỗi");}
    }//GEN-LAST:event_btn_Adjust_DV1ActionPerformed

    private void tb_DVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DVMouseClicked
      int index = tb_DV.getSelectedRow();
       if(evt.getClickCount()==2) {
       tb_DV.clearSelection();
       txb_TenDV.setText("");
       txb_GiaDV.setText("");
       btn_Add_DV.setEnabled(true);
       btn_Delete_DV.setEnabled(false);
       btn_Adjust_DV.setEnabled(false);
       }
       else {
       btn_Add_DV.setEnabled(false);
       btn_Delete_DV.setEnabled(true);
       btn_Adjust_DV.setEnabled(true);
  
       //DefaultTableModel Tablemodel = (DefaultTableModel) tb_DV1.getModel();
      
       txb_TenDV.setText((String)tb_DV.getValueAt(index,1));
       txb_GiaDV.setText((String)tb_DV.getValueAt(index,2));
       }
    }//GEN-LAST:event_tb_DVMouseClicked

    private void btn_Add_DVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_DVActionPerformed
         int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn thêm","Thêm dữ liệu",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.NO_OPTION) return;
        Connection con = model.GetCon();
        String TenDV = txb_TenDV.getText();
        String DonGia = txb_GiaDV.getText();
        String sql = "EXEC ThemDichVu ?,?";
        try{
            PreparedStatement pres = con.prepareStatement(sql);
            pres.setString(1,TenDV);
            pres.setInt(2,Integer.parseInt(DonGia));

            pres.executeUpdate();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            DefaultTableModel Tablemodel = (DefaultTableModel) tb_DV.getModel();
            String [] row = {Integer.toString(Tablemodel.getRowCount()+1),TenDV,DonGia};
            Tablemodel.addRow(row);
            DichVu = model.LayMaDichVu();
            
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, "Lỗi");}
                 
    }//GEN-LAST:event_btn_Add_DVActionPerformed

    private void btn_Delete_DVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Delete_DVActionPerformed
       int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa","Xóa dữ liệu",JOptionPane.YES_NO_OPTION);
       if(ret == JOptionPane.NO_OPTION) return;
       Connection con = model.GetCon();
       int index = tb_DV.getSelectedRow();
       
       int MaDV = DichVu.get(index) ;

       String sql = "DELETE FROM DICHVU WHERE MaDV=?";
       DefaultTableModel Tablemodel = (DefaultTableModel) tb_DV.getModel();
       try{
            PreparedStatement pres = con.prepareStatement(sql);
            pres.setInt(1,MaDV);
            pres.executeUpdate();
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            Tablemodel.removeRow(tb_DV.getSelectedRow());
            DichVu = model.LayMaDichVu();
            tb_DV.clearSelection();
            txb_TenDV.setText("");
            txb_GiaDV.setText("");
            btn_Add_DV.setEnabled(true);
            btn_Delete_DV.setEnabled(false);
            btn_Adjust_DV.setEnabled(false);
            for(int i=0;i<Tablemodel.getRowCount();i++) {
                tb_DV.setValueAt(i+1, i, 0);
            
            }
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, "Lỗi");}
    }//GEN-LAST:event_btn_Delete_DVActionPerformed

    private void btn_Adjust_DVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Adjust_DVActionPerformed
       int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn sửa","Sửa dữ liệu",JOptionPane.YES_NO_OPTION);
       if(ret == JOptionPane.NO_OPTION) return;
       int index = tb_DV.getSelectedRow();
       Connection con = model.GetCon();       
       int MaDV = DichVu.get(index) ;
       String TenDV = txb_TenDV.getText();
       String DonGia = txb_GiaDV.getText();
      
       
       String sql = "UPDATE DICHVU SET TenDV=?,DonGia=? WHERE MaDV=?";
       try{
            PreparedStatement pres = con.prepareStatement(sql);
            pres.setString(1,TenDV);
            pres.setInt(2,Integer.parseInt(DonGia));
            pres.setInt(3,MaDV);
            pres.executeUpdate();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            tb_DV.setValueAt(TenDV, index, 1);
            tb_DV.setValueAt(DonGia, index, 2);
            txb_TenDV.setText("");
            txb_GiaDV.setText("");
            btn_Add_DV.setEnabled(true);
            btn_Delete_DV.setEnabled(false);
            btn_Adjust_DV.setEnabled(false);
        
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, "Lỗi");}
    }//GEN-LAST:event_btn_Adjust_DVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add_DV;
    private javax.swing.JButton btn_Add_DV1;
    private javax.swing.JButton btn_Add_LP;
    private javax.swing.JButton btn_Add_NV;
    private javax.swing.JButton btn_Add_Phong;
    private javax.swing.JButton btn_Adjust_DV;
    private javax.swing.JButton btn_Adjust_DV1;
    private javax.swing.JButton btn_Adjust_LP;
    private javax.swing.JButton btn_Adjust_NV;
    private javax.swing.JButton btn_Adjust_Phong;
    private javax.swing.JButton btn_Delete_DV;
    private javax.swing.JButton btn_Delete_DV1;
    private javax.swing.JButton btn_Delete_LP;
    private javax.swing.JButton btn_Delete_NV;
    private javax.swing.JButton btn_Delete_Phong;
    private javax.swing.JButton btn_Salary;
    private javax.swing.JComboBox<String> combob_LoaiPhong;
    private javax.swing.JComboBox<String> combob_TinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JPanel tabpn_ChucVu;
    private javax.swing.JPanel tabpn_DV;
    private javax.swing.JPanel tabpn_NV;
    private javax.swing.JPanel tabpn_Phong;
    private javax.swing.JTable tb_DV;
    private javax.swing.JTable tb_DV1;
    private javax.swing.JTable tb_LPhong;
    private javax.swing.JTable tb_NV;
    private javax.swing.JTable tb_Phong;
    private javax.swing.JTextField txb_GhiChu;
    private javax.swing.JTextField txb_GiaDV;
    private javax.swing.JTextField txb_GiaDV1;
    private javax.swing.JTextField txb_GiaLPhong;
    private javax.swing.JTextField txb_SoPhong;
    private javax.swing.JTextField txb_SucChua;
    private javax.swing.JTextField txb_TenDV;
    private javax.swing.JTextField txb_TenDV1;
    private javax.swing.JTextField txb_TenLPhong;
    // End of variables declaration//GEN-END:variables
}
