/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotelmanager;

/**
 *
 * @author Admins
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Name = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_Main = new javax.swing.JPanel();
        btn_CheckIN = new javax.swing.JButton();
        btn_CheckOUT = new javax.swing.JButton();
        btn_CheckOUT1 = new javax.swing.JButton();
        btn_Admin = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabpn_PhongThue = new javax.swing.JPanel();
        comb_ThongTin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_RoomInfo = new javax.swing.JTable();
        txb_TimKiem = new javax.swing.JTextField();
        btn_Find = new javax.swing.JButton();
        tabpn_Phong = new javax.swing.JScrollPane();
        tb_Room = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Màn hình chính");
        setBackground(new java.awt.Color(255, 204, 204));
        setName("fMenu"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        pn_Name.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("SVN-Nexa Rush Handmade Extended", 0, 24)); // NOI18N
        jLabel1.setText("KHÁCH SẠN ");

        jLabel2.setFont(new java.awt.Font("SVN-Nexa Rush Handmade Extended", 0, 36)); // NOI18N
        jLabel2.setText("PHÙ HỢP TIÊU CHUẨN CỘNG ĐỒNG");

        javax.swing.GroupLayout pn_NameLayout = new javax.swing.GroupLayout(pn_Name);
        pn_Name.setLayout(pn_NameLayout);
        pn_NameLayout.setHorizontalGroup(
            pn_NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_NameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_NameLayout.setVerticalGroup(
            pn_NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_NameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pn_Main.setBackground(new java.awt.Color(255, 204, 204));

        btn_CheckIN.setBackground(new java.awt.Color(255, 204, 204));
        btn_CheckIN.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_CheckIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/2931187_door_enter_exit_in_leave_icon.png"))); // NOI18N
        btn_CheckIN.setText("Nhận phòng");
        btn_CheckIN.setBorder(null);

        btn_CheckOUT.setBackground(new java.awt.Color(255, 204, 204));
        btn_CheckOUT.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_CheckOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/2931188_door_enter_exit_leave_out_icon.png"))); // NOI18N
        btn_CheckOUT.setText(" Trả phòng");
        btn_CheckOUT.setBorder(null);

        btn_CheckOUT1.setBackground(new java.awt.Color(255, 204, 204));
        btn_CheckOUT1.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_CheckOUT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/2931177_output_print_printer_icon.png"))); // NOI18N
        btn_CheckOUT1.setText("Báo cáo");
        btn_CheckOUT1.setBorder(null);

        btn_Admin.setBackground(new java.awt.Color(255, 204, 204));
        btn_Admin.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 36)); // NOI18N
        btn_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/2203549_admin_avatar_human_login_user_icon.png"))); // NOI18N
        btn_Admin.setBorder(null);

        jTabbedPane1.setBackground(new java.awt.Color(242, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("SVN-Nexa Rush Sans Black", 0, 24)); // NOI18N

        tabpn_PhongThue.setBackground(new java.awt.Color(252, 204, 204));

        comb_ThongTin.setFont(new java.awt.Font("SVN-Nexa Light", 0, 36)); // NOI18N

        tb_RoomInfo.setBackground(new java.awt.Color(255, 204, 204));
        tb_RoomInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_RoomInfo.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_RoomInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Phòng", "Tên khách", "Thời gian thuê", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_RoomInfo.setGridColor(new java.awt.Color(0, 0, 0));
        tb_RoomInfo.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_RoomInfo.setShowGrid(false);
        tb_RoomInfo.setShowHorizontalLines(true);
        tb_RoomInfo.setShowVerticalLines(true);
        tb_RoomInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_RoomInfo);
        if (tb_RoomInfo.getColumnModel().getColumnCount() > 0) {
            tb_RoomInfo.getColumnModel().getColumn(0).setResizable(false);
            tb_RoomInfo.getColumnModel().getColumn(1).setResizable(false);
            tb_RoomInfo.getColumnModel().getColumn(2).setResizable(false);
            tb_RoomInfo.getColumnModel().getColumn(3).setResizable(false);
        }

        txb_TimKiem.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        btn_Find.setBackground(new java.awt.Color(255, 204, 204));
        btn_Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/172546_search_icon.png"))); // NOI18N
        btn_Find.setBorder(null);

        javax.swing.GroupLayout tabpn_PhongThueLayout = new javax.swing.GroupLayout(tabpn_PhongThue);
        tabpn_PhongThue.setLayout(tabpn_PhongThueLayout);
        tabpn_PhongThueLayout.setHorizontalGroup(
            tabpn_PhongThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabpn_PhongThueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comb_ThongTin, 0, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Find)
                .addContainerGap())
            .addGroup(tabpn_PhongThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabpn_PhongThueLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tabpn_PhongThueLayout.setVerticalGroup(
            tabpn_PhongThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabpn_PhongThueLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(tabpn_PhongThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txb_TimKiem)
                    .addComponent(btn_Find, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comb_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 527, Short.MAX_VALUE))
            .addGroup(tabpn_PhongThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabpn_PhongThueLayout.createSequentialGroup()
                    .addContainerGap(79, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Phòng cho thuê", tabpn_PhongThue);

        tb_Room.setBackground(new java.awt.Color(255, 204, 204));
        tb_Room.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_Room.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_Room.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Loại phòng", "Phòng", "Sức chứa", "Tình trạng", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Room.setGridColor(new java.awt.Color(0, 0, 0));
        tb_Room.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_Room.setShowGrid(false);
        tb_Room.setShowHorizontalLines(true);
        tb_Room.setShowVerticalLines(true);
        tb_Room.getTableHeader().setReorderingAllowed(false);
        tabpn_Phong.setViewportView(tb_Room);
        if (tb_Room.getColumnModel().getColumnCount() > 0) {
            tb_Room.getColumnModel().getColumn(0).setResizable(false);
            tb_Room.getColumnModel().getColumn(1).setResizable(false);
            tb_Room.getColumnModel().getColumn(2).setResizable(false);
            tb_Room.getColumnModel().getColumn(3).setResizable(false);
        }

        jTabbedPane1.addTab("Phòng", tabpn_Phong);

        javax.swing.GroupLayout pn_MainLayout = new javax.swing.GroupLayout(pn_Main);
        pn_Main.setLayout(pn_MainLayout);
        pn_MainLayout.setHorizontalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MainLayout.createSequentialGroup()
                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_MainLayout.createSequentialGroup()
                        .addContainerGap(103, Short.MAX_VALUE)
                        .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_CheckIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_CheckOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CheckOUT1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(pn_MainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pn_MainLayout.setVerticalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_CheckIN, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_CheckOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_CheckOUT1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_MainLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Admin;
    private javax.swing.JButton btn_CheckIN;
    private javax.swing.JButton btn_CheckOUT;
    private javax.swing.JButton btn_CheckOUT1;
    private javax.swing.JButton btn_Find;
    private javax.swing.JComboBox<String> comb_ThongTin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pn_Main;
    private javax.swing.JPanel pn_Name;
    private javax.swing.JScrollPane tabpn_Phong;
    private javax.swing.JPanel tabpn_PhongThue;
    private javax.swing.JTable tb_Room;
    private javax.swing.JTable tb_RoomInfo;
    private javax.swing.JTextField txb_TimKiem;
    // End of variables declaration//GEN-END:variables
}
