/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotelmanager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admins
 */
public class Salary extends javax.swing.JFrame {

    /**
     * Creates new form Salary
     */
    private final Source_code model = new Source_code();
    private  List<Integer> Luong ;
    //Hàm reset dữ liệu
    public void restart() {
        Luong = model.LayMaBCLuong();
        List<String> ThoiGian = new ArrayList<>();
        for(int i:Luong) {
            ThoiGian.add(model.LayThang(i));
         }
        cb_thang.setModel(new javax.swing.DefaultComboBoxModel<>(ThoiGian.toArray(String[]::new)));
        DefaultTableModel tmodel = (DefaultTableModel) tb_NV.getModel();
        tmodel.setRowCount(0);
        String sql = "EXEC Update_BangLuong";
        Connection con = model.GetCon();
        try {
            Statement pres = con.createStatement();
            pres.executeUpdate(sql);
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, e);}
    }
    
    public Salary() {
        initComponents();
        String sql = "EXEC KT_BCL";
        Connection con = model.GetCon();
        try{
           
          Statement pres = con.createStatement();
          pres.executeUpdate(sql);
     
   
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, e);}
        restart();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_NV = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        btn_XN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cb_thang = new javax.swing.JComboBox<>();
        Text_Tong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 204, 204));

        jLabel1.setFont(new java.awt.Font("SVN-Nexa Rush Handmade Extended", 1, 48)); // NOI18N
        jLabel1.setText("Lương");

        jScrollPane1.setFont(new java.awt.Font("SVN-Nexa Light", 0, 24)); // NOI18N

        tb_NV.setBackground(new java.awt.Color(255, 204, 204));
        tb_NV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_NV.setFont(new java.awt.Font("SVN-Nexa Light", 0, 12)); // NOI18N
        tb_NV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Nhân viên", "Chức vụ", "Lương cơ bản", "Phát sinh", "Thành tiền", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_NV.setGridColor(new java.awt.Color(0, 0, 0));
        tb_NV.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tb_NV.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_NV.setShowGrid(false);
        tb_NV.setShowHorizontalLines(true);
        tb_NV.setShowVerticalLines(true);
        tb_NV.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_NV);

        jLabel2.setFont(new java.awt.Font("SVN-Nexa Light", 1, 30)); // NOI18N
        jLabel2.setText("Thời gian:");

        btn_Back.setBackground(new java.awt.Color(252, 204, 204));
        btn_Back.setFont(new java.awt.Font("SVN-Nexa Light", 0, 36)); // NOI18N
        btn_Back.setIcon(new javax.swing.ImageIcon("D:\\Hotel_Manager\\HotelManager\\src\\main\\java\\Icon\\352020_arrow_back_icon.png")); // NOI18N
        btn_Back.setBorder(null);
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_XN.setBackground(new java.awt.Color(252, 204, 204));
        btn_XN.setFont(new java.awt.Font("SVN-Nexa Light", 0, 36)); // NOI18N
        btn_XN.setForeground(new java.awt.Color(51, 204, 0));
        btn_XN.setIcon(new javax.swing.ImageIcon("D:\\Hotel_Manager\\HotelManager\\src\\main\\java\\Icon\\1398912_circle_correct_mark_success_tick_icon.png")); // NOI18N
        btn_XN.setText("Xác Nhận");
        btn_XN.setBorder(null);
        btn_XN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SVN-Nexa Light", 1, 30)); // NOI18N
        jLabel3.setText("Tổng:");

        cb_thang.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cb_thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_thangActionPerformed(evt);
            }
        });

        Text_Tong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Text_Tong.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_Back))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btn_XN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Text_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_Back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Text_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_XN)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_BackActionPerformed

    //Lấy bảng lương tương ứng với tháng
    private void cb_thangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_thangActionPerformed
       restart();
       int index = cb_thang.getSelectedIndex();
       int MaBC = Luong.get(index);
       String sql = "EXEC HienThiChiTietBaoCaoLuong ?";
       Connection con = model.GetCon();
       String row[] = new String[7];
       DefaultTableModel Tablemodel = (DefaultTableModel) tb_NV.getModel();
       try{
           
          PreparedStatement pres = con.prepareStatement(sql);
          pres.setInt(1,MaBC);
          
          ResultSet rs = pres.executeQuery();
         
          while(rs.next()) {
              row[0] = Integer.toString(Tablemodel.getRowCount()+1);
              row[1] = rs.getString(1);
              row[2] = rs.getString(2);
              row[3] = rs.getString(3);
              row[4] = rs.getString(4);
              row[5] = rs.getString(5);
              row[6] = rs.getString(6);
              Tablemodel.addRow(row);
          }
        }
        catch(SQLException e) {JOptionPane.showMessageDialog(null, e);}        
    }//GEN-LAST:event_cb_thangActionPerformed

    //Hàm xác nhận
    private void btn_XNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XNActionPerformed
        int TongTien = 0;
        int index = cb_thang.getSelectedIndex();
        int Ma_BC = Luong.get(index);
      
        List<Integer> MaCT_Luong = model.LayMaBCLuong(Ma_BC);
        String sql = "EXEC UpdatePhatSinhBangCTLuong ?,?,?,? ";
        String Manv = "";
        Connection con = model.GetCon();
        for(int i =0;i<tb_NV.getRowCount();i++){
            int SoTT = Integer.parseInt((String) tb_NV.getValueAt(i, 0));
            int MaCT_BC = MaCT_Luong.get(SoTT-1);
            Manv = model.LayThuocTinhCTLuong(MaCT_BC,"MaNV");
            int PhatSinh = Integer.parseInt((String) tb_NV.getValueAt(i, 4));
            String GhiChu = (String) tb_NV.getValueAt(i, 6);
            TongTien +=   Integer.parseInt((String) tb_NV.getValueAt(i, 5)) + PhatSinh;
            try{
           
                PreparedStatement pres = con.prepareStatement(sql);
                pres.setInt(1,PhatSinh);
                pres.setInt(2,Ma_BC);
                pres.setInt(3,Integer.parseInt(Manv));
                pres.setString(4,GhiChu);
                pres.executeUpdate();
          
             }
            catch(SQLException e) {JOptionPane.showMessageDialog(null, e);}
            tb_NV.setValueAt(model.LayThuocTinhCTLuong(MaCT_BC,"Thanh_Tien"),i, 5);
        }
        Text_Tong.setText(String.valueOf(TongTien));
        
    }//GEN-LAST:event_btn_XNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_Tong;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_XN;
    private javax.swing.JComboBox<String> cb_thang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_NV;
    // End of variables declaration//GEN-END:variables
}
